package com.kikirikii.model;

public enum Event {
    EVENT_FRIEND_REQUESTED,
    EVENT_FRIEND_CANCELLED,
    EVENT_FRIEND_ACCEPTED,
    EVENT_FRIEND_IGNORED,
    EVENT_FRIEND_DELETED,
    EVENT_FRIEND_BLOCKED,
    EVENT_FRIEND_UNBLOCKED,
    EVENT_FOLLOWER_BLOCKED,
    EVENT_FOLLOWER_UNBLOCKED,
    EVENT_FOLLOWER_ADDED,
    EVENT_FOLLOWER_DELETED
}
